/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.42
 * Generated at: 2013-08-02 11:47:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.example;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mvc_005fupload_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/jsp/example/../include/common.jsp", Long.valueOf(1375349684388L));
    _jspx_dependants.put("/WEB-INF/tld/spring.tld", Long.valueOf(1375077153211L));
    _jspx_dependants.put("/WEB-INF/tld/spring-form.tld", Long.valueOf(1375077153210L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fcore_005fset_0026_005fvar_005fvalue_005fscope_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fcore_005fset_0026_005fvar_005fvalue_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fcore_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      if (_jspx_meth_core_005fset_005f0(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_core_005fset_005f1(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_core_005fset_005f2(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_core_005fset_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>HTML5拖拽文件上传</title>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${jspath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jquery-2.0.3.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write(".dashboard_target_box {\r\n");
      out.write("    width: 250px;\r\n");
      out.write("    height: 105px;\r\n");
      out.write("    border: 3px dashed #E5E5E5;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    z-index: 2000;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    cursor: pointer\r\n");
      out.write("}\r\n");
      out.write("  \r\n");
      out.write(".dashboard_target_box.over {\r\n");
      out.write("    border: 3px dashed #000;\r\n");
      out.write("    background: #ffa\r\n");
      out.write("}\r\n");
      out.write("  \r\n");
      out.write(".dashboard_target_messages_container {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    margin: 12px 0 0;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    height: 44px;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    z-index: 2000\r\n");
      out.write("}\r\n");
      out.write("  \r\n");
      out.write(".dashboard_target_box_message {\r\n");
      out.write("    position: relative;\r\n");
      out.write("    margin: 4px auto;\r\n");
      out.write("    font: 15px/18px helvetica, arial, sans-serif;\r\n");
      out.write("    font-size: 15px;\r\n");
      out.write("    color: #999;\r\n");
      out.write("    font-weight: normal;\r\n");
      out.write("    width: 150px;\r\n");
      out.write("    line-height: 20px\r\n");
      out.write("}\r\n");
      out.write("  \r\n");
      out.write(".dashboard_target_box.over #dtb-msg1 {\r\n");
      out.write("    color: #000;\r\n");
      out.write("    font-weight: bold\r\n");
      out.write("}\r\n");
      out.write("  \r\n");
      out.write(".dashboard_target_box.over #dtb-msg3 {\r\n");
      out.write("    color: #ffa;\r\n");
      out.write("    border-color: #ffa\r\n");
      out.write("}\r\n");
      out.write("  \r\n");
      out.write("#dtb-msg2 {\r\n");
      out.write("    color: orange\r\n");
      out.write("}\r\n");
      out.write("  \r\n");
      out.write("#dtb-msg3 {\r\n");
      out.write("    display: block;\r\n");
      out.write("    border-top: 1px #EEE dotted;\r\n");
      out.write("    padding: 8px 24px\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("        //设计一段比较流行的滑动样式\r\n");
      out.write("        $('#drop_zone_home').hover(function() {\r\n");
      out.write("            $(this).children('p').stop().animate({\r\n");
      out.write("                top : '0px'\r\n");
      out.write("            }, 200);\r\n");
      out.write("        }, function() {\r\n");
      out.write("            $(this).children('p').stop().animate({\r\n");
      out.write("                top : '-44px'\r\n");
      out.write("            }, 200);\r\n");
      out.write("        });\r\n");
      out.write("  \r\n");
      out.write("        //要想实现拖拽，首页需要阻止浏览器默认行为，一个四个事件。\r\n");
      out.write("        $(document).on({\r\n");
      out.write("            dragleave : function(e) { //拖离\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                $('.dashboard_target_box').removeClass('over');\r\n");
      out.write("            },\r\n");
      out.write("            drop : function(e) { //拖后放\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("            },\r\n");
      out.write("            dragenter : function(e) { //拖进\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                $('.dashboard_target_box').addClass('over');\r\n");
      out.write("            },\r\n");
      out.write("            dragover : function(e) { //拖来拖去\r\n");
      out.write("                e.preventDefault();\r\n");
      out.write("                $('.dashboard_target_box').addClass('over');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("  \r\n");
      out.write("        //================上传的实现\r\n");
      out.write("        var box = document.getElementById('target_box'); //获得到框体\r\n");
      out.write("        box.addEventListener(\"drop\", function(e) {\r\n");
      out.write("            e.preventDefault(); //取消默认浏览器拖拽效果\r\n");
      out.write("          \r\n");
      out.write("            var fileList = e.dataTransfer.files; //获取文件对象\r\n");
      out.write("            //fileList.length 用来获取文件的长度（其实是获得文件数量）\r\n");
      out.write("            //检测是否是拖拽文件到页面的操作\r\n");
      out.write("            if (fileList.length == 0) {\r\n");
      out.write("                $('.dashboard_target_box').removeClass('over');\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("            //检测文件是不是图片\r\n");
      out.write("            /*if (fileList[0].type.indexOf('image') === -1) {\r\n");
      out.write("                $('.dashboard_target_box').removeClass('over');\r\n");
      out.write("                return;\r\n");
      out.write("            }*/\r\n");
      out.write("  \r\n");
      out.write("            //var img = window.webkitURL.createObjectURL(fileList[0]);\r\n");
      out.write("            //拖拉图片到浏览器，可以实现预览功能\r\n");
      out.write("            xhr = new XMLHttpRequest();\r\n");
      out.write("            xhr.open(\"post\", \"/upload\", true);\r\n");
      out.write("            xhr.setRequestHeader(\"X-Requested-With\", \"XMLHttpRequest\");\r\n");
      out.write("  \r\n");
      out.write("            var fd = new FormData();\r\n");
      out.write("            fd.append('files', fileList[0]);\r\n");
      out.write("  \r\n");
      out.write("            xhr.send(fd);\r\n");
      out.write("        }, false);\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("  \r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"target_box\" class=\"dashboard_target_box\">\r\n");
      out.write("        <div id=\"drop_zone_home\" class=\"dashboard_target_messages_container\">\r\n");
      out.write("            <p id=\"dtb-msg2\" class=\"dashboard_target_box_message\"\r\n");
      out.write("                style=\"top: -44px\">\r\n");
      out.write("                选择你的图片<br> 开始上传\r\n");
      out.write("            </p>\r\n");
      out.write("            <p id=\"dtb-msg1\" class=\"dashboard_target_box_message\"\r\n");
      out.write("                style=\"top: -44px\">\r\n");
      out.write("                拖动图片到<br> 这里\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_core_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_core_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fcore_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_core_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_core_005fset_005f0.setParent(null);
    // /WEB-INF/jsp/example/../include/common.jsp(8,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_core_005fset_005f0.setVar("webcontext");
    // /WEB-INF/jsp/example/../include/common.jsp(8,0) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_core_005fset_005f0.setScope("request");
    // /WEB-INF/jsp/example/../include/common.jsp(8,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_core_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/example/../include/common.jsp(8,0) '${pageContext.request.contextPath}'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_core_005fset_005f0 = _jspx_th_core_005fset_005f0.doStartTag();
    if (_jspx_th_core_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcore_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_core_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fcore_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_core_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_core_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_core_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fcore_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_core_005fset_005f1.setPageContext(_jspx_page_context);
    _jspx_th_core_005fset_005f1.setParent(null);
    // /WEB-INF/jsp/example/../include/common.jsp(9,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_core_005fset_005f1.setVar("imagepath");
    // /WEB-INF/jsp/example/../include/common.jsp(9,0) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_core_005fset_005f1.setScope("request");
    // /WEB-INF/jsp/example/../include/common.jsp(9,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_core_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/example/../include/common.jsp(9,0) '${webcontext}/images'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${webcontext}/images",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_core_005fset_005f1 = _jspx_th_core_005fset_005f1.doStartTag();
    if (_jspx_th_core_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcore_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_core_005fset_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fcore_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_core_005fset_005f1);
    return false;
  }

  private boolean _jspx_meth_core_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_core_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fcore_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_core_005fset_005f2.setPageContext(_jspx_page_context);
    _jspx_th_core_005fset_005f2.setParent(null);
    // /WEB-INF/jsp/example/../include/common.jsp(10,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_core_005fset_005f2.setVar("csspath");
    // /WEB-INF/jsp/example/../include/common.jsp(10,0) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_core_005fset_005f2.setScope("request");
    // /WEB-INF/jsp/example/../include/common.jsp(10,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_core_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/example/../include/common.jsp(10,0) '${webcontext}/css'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${webcontext}/css",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_core_005fset_005f2 = _jspx_th_core_005fset_005f2.doStartTag();
    if (_jspx_th_core_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcore_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_core_005fset_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fcore_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_core_005fset_005f2);
    return false;
  }

  private boolean _jspx_meth_core_005fset_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  core:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_core_005fset_005f3 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fcore_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_core_005fset_005f3.setPageContext(_jspx_page_context);
    _jspx_th_core_005fset_005f3.setParent(null);
    // /WEB-INF/jsp/example/../include/common.jsp(11,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_core_005fset_005f3.setVar("jspath");
    // /WEB-INF/jsp/example/../include/common.jsp(11,0) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_core_005fset_005f3.setScope("request");
    // /WEB-INF/jsp/example/../include/common.jsp(11,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_core_005fset_005f3.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/example/../include/common.jsp(11,0) '${webcontext}/javascript'",_el_expressionfactory.createValueExpression(_jspx_page_context.getELContext(),"${webcontext}/javascript",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_core_005fset_005f3 = _jspx_th_core_005fset_005f3.doStartTag();
    if (_jspx_th_core_005fset_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fcore_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_core_005fset_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fcore_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_core_005fset_005f3);
    return false;
  }
}
